id = "zed-lua"
name = "Zed Lua"
version = "0.0.1"
schema_version = 1
authors = ["Sol Wolf <wolfendenbuild@gmail.com>"]
description = "Adds Lua scripting support to the Zed code editor."
repository = "https://github.com/your-name/my-zed-extension"
